// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
//  This file reads from data/site.json and exports typed
//  helpers used throughout the website.
//
//  ✅ You ONLY need to edit:  data/site.json
//     Do NOT edit this file unless you are a developer.
// ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
import raw from '@/data/site.json';

export const siteConfig = {
  // Company
  name:        raw.company.name,
  tagline:     raw.company.tagline,
  description: raw.company.description,

  // Contact
  email:   raw.contact.email,
  phone:   raw.contact.phone,
  address: raw.contact.address,

  // WhatsApp
  whatsapp:        raw.whatsapp.number,
  whatsappMessage: raw.whatsapp.message,

  // Social
  social: raw.social,

  // Logo
  logoPath:   raw.logo.path as string | null,
  logoAlt:    raw.logo.alt,
  logoWidth:  raw.logo.width,
  logoHeight: raw.logo.height,

  // Footer
  copyrightYear: raw.footer.copyrightYear,

  // Nav links (static — change in this file if needed)
  navLinks: [
    { label: 'Home',       href: '#hero' },
    { label: 'About',      href: '#about' },
    { label: 'Services',   href: '#services' },
    { label: 'E-Commerce', href: '#ecommerce' },
    { label: 'LMS',        href: '#lms-hero' },
    { label: 'Contact',    href: '#contact' },
  ],

  // Footer link columns (static — change in this file if needed)
  footerLinks: {
    Services: [
      'AI Development',
      'Web & Mobile Apps',
      'Enterprise LMS',
      'Global Commerce',
      'CRM Systems',
    ],
    Company: [
      'About Us',
      'Our Approach',
      'Careers',
      'Blog',
      'Case Studies',
    ],
  },
} as const;

// ── WhatsApp deep-link builder ────────────────────────────
export function whatsappUrl() {
  const msg = encodeURIComponent(raw.whatsapp.message);
  return `https://wa.me/${raw.whatsapp.number}?text=${msg}`;
}
